package entity;

import be.bittich.dynaorm.annotation.MetaColumn;
import be.bittich.dynaorm.annotation.PrimaryKey;
import be.bittich.dynaorm.annotation.TableFromDB;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
@TableFromDB(tableName = "city")
public class City {

    @PrimaryKey(autoGenerated = true)
    private int id;
    private String zip;
    @MetaColumn(columnName = "name")
    private String name;

    public City() {

    }

    public City(int id) {
        this.id = id;
    }
    
    //gette && setter...

    public City(String zip, String name) {
        this.zip = zip;
        this.name = name;
    }

    public City(int id, String zip, String name) {
        this.id = id;
        this.zip = zip;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getZip() {
        return zip;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

}
