/*
 * Copyright 2014 Evoliris.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package entity;


import be.bittich.dynaorm.annotation.MetaColumn;
import be.bittich.dynaorm.annotation.PrimaryKey;
import be.bittich.dynaorm.annotation.TableFromDB;

/**
 *
 * @author Evoliris
 */
@TableFromDB(tableName = "country_t")
public class Country {

    @PrimaryKey(autoGenerated = true, label = "country_id")
    private int id;
    private String iso2;
    @MetaColumn(columnName = "short_name")
    private String shortName;
    @MetaColumn(columnName = "long_name")
    private String longName;
    private String iso3;
    @MetaColumn(columnName = "numcode")
    private String numCode;
    @MetaColumn(columnName = "un_member")
    private String unMember;
    @MetaColumn(columnName = "calling_code")
    private String callingCode;
    @MetaColumn(columnName = "cctld")
    private String cctId;

    public Country() {
    }

    public Country(Integer id) {
        this.id=id;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the iso2
     */
    public String getIso2() {
        return iso2;
    }

    /**
     * @param iso2 the iso2 to set
     */
    public void setIso2(String iso2) {
        this.iso2 = iso2;
    }

    /**
     * @return the shortName
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * @param shortName the shortName to set
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * @return the longName
     */
    public String getLongName() {
        return longName;
    }

    /**
     * @param longName the longName to set
     */
    public void setLongName(String longName) {
        this.longName = longName;
    }

    /**
     * @return the iso3
     */
    public String getIso3() {
        return iso3;
    }

    /**
     * @param iso3 the iso3 to set
     */
    public void setIso3(String iso3) {
        this.iso3 = iso3;
    }

    /**
     * @return the numCode
     */
    public String getNumCode() {
        return numCode;
    }

    /**
     * @param numCode the numCode to set
     */
    public void setNumCode(String numCode) {
        this.numCode = numCode;
    }

    /**
     * @return the unMember
     */
    public String getUnMember() {
        return unMember;
    }

    /**
     * @param unMember the unMember to set
     */
    public void setUnMember(String unMember) {
        this.unMember = unMember;
    }

    /**
     * @return the callingCode
     */
    public String getCallingCode() {
        return callingCode;
    }

    /**
     * @param callingCode the callingCode to set
     */
    public void setCallingCode(String callingCode) {
        this.callingCode = callingCode;
    }

    /**
     * @return the cctId
     */
    public String getCctId() {
        return cctId;
    }

    /**
     * @param cctId the cctId to set
     */
    public void setCctId(String cctId) {
        this.cctId = cctId;
    }

}
